version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    networks:
      - backend
    env_file: 
      - "db.env"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
networks: 
  backend: