version: '3.1'
services:
  postgres:
    container_name: postgres
    restart: always
    expose:
      - "5432"
    networks:
      - backend
    env_file: 
      - "db.env"
  app:
    container_name: app
    build: .
    restart: always
    depends_on:
      - postgres
    ports: 
      - "80:80"
    networks:
      - backend
    environment: 
      PG.HOST: postgres
networks: 
  backend: